### ISSUE TITLE
running the latest code complained of no `sb_users_definition` and `sb_user_groups_definitions`

### ISSUE THREAD

**Issue by simbo1905** [orachide/ansible-role-springboot#3]
Running the latest code complained that there was no  `sb_users_definition` or `sb_user_groups_definitions`. Googling I managed to find some examples. My playbooks work with:

```
    sb_users_definition:
      - name: Simple Spring Boot App User
        username: sbuser
        groups: [sbgroup]
    sb_user_groups_definitions:
      - name: sbgroup
    sb_app_user: sbuser
    sb_app_user_group: sbgroup
```

Note that it requires the list definitions to create the users and groups then a specific user and group to use. 

The `check_vars.yml` didn't check those variables are there so I added that myself with: 

```
- name: "Check vars | Assert sb_users_definition is defined"
  assert:
    that:
      - "sb_users_definition is defined"
    msg: "sb_users_definition must be defined"

- name: "Check vars | Assert sb_user_groups_definitions is defined"
  assert:
    that:
      - "sb_user_groups_definitions is defined"
    msg: "sb_user_groups_definitions must be defined"
```
